const express = require('express')
const multer  = require('multer')
const fs      = require('fs')
const path    = require('path')

const app      = express()
const PORT     = 3001
const ROOT     = __dirname
const DATA_FILE = path.join(ROOT, 'data', 'data.json')
const DATA_JS   = path.join(ROOT, 'data', 'data.js')

app.use(express.json({ limit: '10mb' }))
app.use(express.static(ROOT))

// ── Helpers ──────────────────────────────────────────────────────────────────

function readData() {
  return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'))
}

function writeData(data) {
  fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf8')
  fs.writeFileSync(
    DATA_JS,
    '// AUTO-GENERATED by admin.js — do not edit manually\n' +
    '// To update: npm run admin  →  http://localhost:' + PORT + '/admin.html\n' +
    'window.PORTFOLIO_DATA=' + JSON.stringify(data) + ';\n',
    'utf8'
  )
}

// ── Image upload ──────────────────────────────────────────────────────────────

const storage = multer.diskStorage({
  destination(req, file, cb) {
    const dir = path.join(ROOT, 'data', 'images', req.params.id)
    fs.mkdirSync(dir, { recursive: true })
    cb(null, dir)
  },
  filename(req, file, cb) {
    const safe = file.originalname.replace(/[^\w.\-]/g, '_')
    cb(null, `${Date.now()}_${safe}`)
  }
})
const upload = multer({ storage })

// ── Routes ────────────────────────────────────────────────────────────────────

app.get('/api/data', (_req, res) => {
  try {
    res.json(readData())
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

app.post('/api/data', (req, res) => {
  try {
    writeData(req.body)
    res.json({ ok: true })
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

app.post('/api/upload/:id', upload.single('image'), (req, res) => {
  res.json({ path: `data/images/${req.params.id}/${req.file.filename}` })
})

app.delete('/api/image', (req, res) => {
  try {
    const abs = path.join(ROOT, req.body.path)
    if (fs.existsSync(abs)) fs.unlinkSync(abs)
  } catch (_) { /* ignore */ }
  res.json({ ok: true })
})

// ── Start ─────────────────────────────────────────────────────────────────────

if (!fs.existsSync(path.join(ROOT, 'data'))) {
  fs.mkdirSync(path.join(ROOT, 'data', 'images'), { recursive: true })
}

app.listen(PORT, () => {
  console.log('\n  Portfolio Admin\n')
  console.log(`  Portfolio  ->  http://localhost:${PORT}`)
  console.log(`  Admin      ->  http://localhost:${PORT}/admin.html\n`)
})
