const express = require('express')
const multer  = require('multer')
const fs      = require('fs')
const path    = require('path')

const app      = express()
const PORT     = 3001
const ROOT     = __dirname
const DATA_FILE = path.join(ROOT, 'data', 'data.json')
const DATA_JS   = path.join(ROOT, 'data', 'data.js')

app.use(express.json({ limit: '10mb' }))
app.use(express.static(ROOT))

// ── Helpers ──────────────────────────────────────────────────────────────────

function readData() {
  return JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'))
}

function writeData(data) {
  fs.writeFileSync(DATA_FILE, JSON.stringify(data, null, 2), 'utf8')
  fs.writeFileSync(
    DATA_JS,
    '// AUTO-GENERATED by admin.js — do not edit manually\n' +
    '// To update: npm run admin  →  http://localhost:' + PORT + '/admin.html\n' +
    'window.PORTFOLIO_DATA=' + JSON.stringify(data) + ';\n',
    'utf8'
  )
}

// ── Image upload ──────────────────────────────────────────────────────────────

const storage = multer.diskStorage({
  destination(req, file, cb) {
    const dir = path.join(ROOT, 'data', 'images', req.params.id)
    fs.mkdirSync(dir, { recursive: true })
    cb(null, dir)
  },
  filename(req, file, cb) {
    if (!req._ts) req._ts = Date.now()
    const safe = file.originalname.replace(/[^\w.\-]/g, '_')
    // if the client already set a timestamped filename (e.g. for thumbs), use it verbatim
    cb(null, /^\d{10,}_/.test(safe) ? safe : `${req._ts}_${safe}`)
  }
})
const upload = multer({ storage })

// ── Routes ────────────────────────────────────────────────────────────────────

app.get('/api/data', (_req, res) => {
  try {
    res.json(readData())
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

app.post('/api/data', (req, res) => {
  try {
    writeData(req.body)
    res.json({ ok: true })
  } catch (e) {
    res.status(500).json({ error: e.message })
  }
})

app.post('/api/upload/:id', upload.any(), (req, res) => {
  const files = req.files || []
  const main  = files.find(f => f.fieldname === 'image')
  if (!main) return res.status(400).json({ error: 'no file' })
  const dir = path.join(ROOT, 'data', 'images', req.params.id)
  for (const variant of ['thumb', 'preview']) {
    const vf = files.find(f => f.fieldname === variant)
    if (!vf) continue
    const target = path.join(dir, main.filename.replace(/(\.[^.]+)$/, `_${variant}$1`))
    try { fs.renameSync(path.join(dir, vf.filename), target) } catch (_) {}
  }
  res.json({ path: `data/images/${req.params.id}/${main.filename}` })
})

app.delete('/api/image', (req, res) => {
  try {
    const abs = path.join(ROOT, req.body.path)
    if (fs.existsSync(abs)) fs.unlinkSync(abs)
  } catch (_) { /* ignore */ }
  res.json({ ok: true })
})

// ── Start ─────────────────────────────────────────────────────────────────────

if (!fs.existsSync(path.join(ROOT, 'data'))) {
  fs.mkdirSync(path.join(ROOT, 'data', 'images'), { recursive: true })
}

app.listen(PORT, () => {
  console.log('\n  Portfolio Admin\n')
  console.log(`  Portfolio  ->  http://localhost:${PORT}`)
  console.log(`  Admin      ->  http://localhost:${PORT}/admin.html\n`)
})
